apiVersion: v1
kind: Pod
metadata:
  name: todoapp-app
  namespace: todoapp
  labels:
    app: todoapp-app
spec:
  containers:
    - name: todoapp-app
      image: bohn13/todoapp:3.0.1
      ports:
        - containerPort: 8080
      livenessProbe:
        httpGet:
          path: /api/health/
          port: 8080
        initialDelaySeconds: 10
        periodSeconds: 5
      readinessProbe:
        httpGet:
          path: /api/ready/
          port: 8080
        initialDelaySeconds: 15
        periodSeconds: 5
        timeoutSeconds: 3
        failureThreshold: 3